=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/ej05-tarjetacredito/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="documento">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="imagen">
                                <xs:complexType>
                                    <xs:attribute name="foto" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="resumen">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="numero" type="xs:string" />
                                        <xs:element name="validez" type="xs:string" />
                                        <xs:element name="credito" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="piepagina">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="p" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/ej05-tarjetacredito/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="index.css"?>

<!-- © Juan Galisteo | Todos los derechos reservados -->

<documento xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="index.xsd">
  <!-- DNI -->
  <datos>
    <titulo>Tarjeta de crédito</titulo>
    <imagen foto="fotodni"></imagen>
    <resumen>
      <nombre>Juan Bautista Galisteo Marqués</nombre>
      <numero>1033 3691 1963 1247</numero>
      <validez>Valido hasta: 12/25</validez>
      <credito>Debit</credito>
    </resumen>
  </datos>

  <!-- PIE DE PÁGINA -->
  <piepagina>
    <p>© Juan Galisteo | Trabajo de clase: Lenguajes de marcas - DAW</p>
  </piepagina>
</documento>
