=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/ej12-proyectoreal/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="colegio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="estudiante" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellido" type="xs:string" />
                            <xs:element name="fechaNacimiento" type="xs:string" />
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="telefono" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="profesor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellido" type="xs:string" />
                            <xs:element name="especialidad" type="xs:string" />
                            <xs:element name="email" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="curso" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="nivel" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                        <xs:attribute name="profesor" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="piepagina">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="p" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/ej12-proyectoreal/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- © Juan Galisteo | Todos los derechos reservados -->

<colegio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="index.xsd">
    <!-- ESTUDIANTES -->
    <estudiante id="E01">
        <nombre>Carlos</nombre>
        <apellido>Garcia</apellido>
        <fechaNacimiento>17/02/1990</fechaNacimiento>
        <direccion>Calle sin nombre 123, Córdoba</direccion>
        <telefono>+34 600111222</telefono>
    </estudiante>
    <estudiante id="E02">
        <nombre>Juanma</nombre>
        <apellido>Casado</apellido>
        <fechaNacimiento>01/02/1991</fechaNacimiento>
        <direccion>El chimeneón 45, Córdoba</direccion>
        <telefono>+34 600333999</telefono>
    </estudiante>

    <!-- PROFESORES -->
    <profesor id="P01">
        <nombre>Juan</nombre>
        <apellido>Galisteo</apellido>
        <especialidad>Educación Física</especialidad>
        <email>juangalisteo@educacion.com</email>
    </profesor>
    <profesor id="P02">
        <nombre>Inmaculada</nombre>
        <apellido>Galisteo</apellido>
        <especialidad>Itinerario personal para la empleabilidad</especialidad>
        <email>inmaculadagalisteo@educacion.com</email>
    </profesor>

    <!-- CURSOS -->
    <curso id="01" profesor="P01">
        <nombre>Matemáticas</nombre>
        <nivel>Primaria</nivel>
    </curso>
    <curso id="02" profesor="P02"> 
        <nombre>Lengua castellana y literatura</nombre>
        <nivel>Secundaria</nivel>
    </curso>    

    <!-- PIE DE PÁGINA -->
    <piepagina>
        <p>© Juan Galisteo | Colegio Digital</p>
    </piepagina>
</colegio>
