=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/factura/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datosemisor">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="cif" type="xs:string" />
                            <xs:element name="direccion" type="xs:string" />
                            <xs:element name="telefono" type="xs:string" />
                            <xs:element name="correo" type="xs:string" />
                            <xs:element name="horario">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="lunes" type="xs:string" />
                                        <xs:element name="martes" type="xs:string" />
                                        <xs:element name="miercoles" type="xs:string" />
                                        <xs:element name="jueves" type="xs:string" />
                                        <xs:element name="viernes" type="xs:string" />
                                        <xs:element name="sabado" type="xs:string" />
                                        <xs:element name="domingo" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datoscliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="cif" type="xs:string" />
                            <xs:element name="telefono" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="detallefactura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="articulo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="codigoarticulo" type="xs:string" />
                                        <xs:element name="tipo" type="xs:string" />
                                        <xs:element name="descripcion" type="xs:string" />
                                        <xs:element name="cantidad" type="xs:string" />
                                        <xs:element name="oferta" type="xs:string" />
                                        <xs:element name="pvp">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="moneda" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="importe">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="moneda" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="piepagina">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="p" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/factura/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- © Juan Galisteo | Todos los derechos reservados -->

<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="index.xsd">
    <!-- Datos del emisor -->
    <datosemisor>
        <nombre>Librería Luque</nombre>
        <cif>B14874697</cif>
        <direccion>Calle Fray Luis de Granada, 11, 14008 Córdoba</direccion>
        <telefono>+34 957 49 83 33</telefono>
        <correo>librerialuque@librerialuque.es</correo>
        <horario>
            <lunes>09:45 a 13:30 / 17:00 a 20:30</lunes>
            <martes>09:45 a 13:30 / 17:00 a 20:30</martes>
            <miercoles>09:45 a 13:30 / 17:00 a 20:30</miercoles>
            <jueves>09:45 a 13:30 / 17:00 a 20:30</jueves>
            <viernes>09:45 a 13:30 / 17:00 a 20:30</viernes>
            <sabado>10:00 a 13:45 / Tardes cerrado</sabado>
            <domingo>Cerrado</domingo>
        </horario>
    </datosemisor>

    <!-- DATOS CLIENTE -->
    <datoscliente>
        <nombre>Juan Galisteo</nombre>
        <cif>333111222A</cif>
        <telefono>+34 666 333 999</telefono>
    </datoscliente>

    <!-- FACTURA -->
    <detallefactura>
        <articulo>
            <codigoarticulo>AVT</codigoarticulo>
            <tipo>Libro</tipo>
            <descripcion>Geometría Sagrada de la Gran Pirámide</descripcion>
            <cantidad>1</cantidad>
            <oferta>SI</oferta>
            <pvp moneda="EUR">33</pvp>
        </articulo>
        <articulo>
            <codigoarticulo>CP5</codigoarticulo>
            <tipo>Curso</tipo>
            <descripcion>Curso de Numerología y Metafísica</descripcion>
            <cantidad>1</cantidad>
            <oferta>NO</oferta>
            <pvp moneda="EUR">369</pvp>
        </articulo>
    </detallefactura>

    <!-- IMPORTE TOTAL -->
    <importe moneda="EUR" >402</importe>

    <!-- PIE DE PÁGINA -->
    <piepagina>
        <p>© Juan Galisteo | Trabajo de clase: Configuración de Aplicación - DAW</p>
    </piepagina>
</factura>
