=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/ej04-dni/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="documento">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="imagen">
                                <xs:complexType>
                                    <xs:attribute name="foto" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="resumen">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="sexo" type="xs:string" />
                                        <xs:element name="fechanacimiento" type="xs:string" />
                                        <xs:element name="direccion" type="xs:string" />
                                        <xs:element name="ciudad" type="xs:string" />
                                        <xs:element name="dni" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="piepagina">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="p" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/ej04-dni/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/css" href="index.css"?>

<!-- © Juan Galisteo | Todos los derechos reservados -->

<documento xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="index.xsd">
  <!-- DNI -->
  <datos>
    <titulo>Documento Nacional de Identidad</titulo>
    <imagen foto="fotodni"></imagen>
    <resumen>
      <nombre>Juan Bautista Galisteo Marqués</nombre>
      <sexo>Sexo: M  -  Nacionalidad: ESP</sexo>
      <fechanacimiento>01/07/1990</fechanacimiento>
      <direccion>San Francisco de Sales - 7</direccion>
      <ciudad>Córdoba, España</ciudad>
      <dni>12345678A</dni>
    </resumen>
  </datos>

  <!-- PIE DE PÁGINA -->
  <piepagina>
    <p>© Juan Galisteo | Trabajo de clase: Lenguajes de marcas - DAW</p>
  </piepagina>
</documento>
