<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- © Juan Galisteo | Todos los derechos reservados -->

<!DOCTYPE pokeDAW [
  <!ELEMENT pokeDAW (nombre, numeroPokedex, imagen, descripcion, tipo, genero, estado)>
  
  <!-- DTD POKÉMON -->
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT numeroPokedex (#PCDATA)>
  <!ELEMENT imagen (#PCDATA)>
  
  <!ELEMENT descripcion (#PCDATA)>
  <!ELEMENT tipo (#PCDATA)>
  <!ELEMENT genero (#PCDATA)>
  
  <!-- DTD ESTADO -->
  <!ELEMENT estado (habilidades, destreza, nivel, fuerza, faseEvolucion?, puntosVida?)>
  <!ELEMENT habilidades (#PCDATA)>
  <!ELEMENT destreza (#PCDATA)>
  <!ELEMENT nivel (#PCDATA)>
  <!ELEMENT fuerza (#PCDATA)>
  <!ELEMENT faseEvolucion (#PCDATA)>
  <!ELEMENT puntosVida (#PCDATA)>

  <!-- DTD PIE DE PÁGINA -->
  <!ELEMENT piepagina (p)>
  <!ELEMENT p (#PCDATA)>
]>

<pokeDAW>
    <nombre>PokeDAW</nombre>
    <numeroPokedex>369</numeroPokedex>
    <imagen foto="pokedaw"></imagen>
    <descripcion>El Pokémon legendario y más fuerte de todos los tiempos.</descripcion>
    <tipo>psíquico</tipo>
    <genero>masculino</genero>

    <estado>
        <habilidades>Inteligencia, Sabiduría, Velocidad, Resistencia, Autodeterminación</habilidades>
        <destreza>33</destreza>
        <nivel>100</nivel>
        <fuerza>69</fuerza>
        <faseEvolucion>3</faseEvolucion>
        <puntosVida>127</puntosVida>
    </estado>

        <!-- PIE DE PÁGINA -->
    <piepagina>
        <p>© Juan Galisteo | Trabajo de clase: Configuración de Aplicación - DAW</p>
    </piepagina>
</pokeDAW>
