=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/ej09-pokeDAW/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pokeDAW">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="numeroPokedex" type="xs:string" />
                <xs:element name="imagen">
                    <xs:complexType>
                        <xs:attribute name="foto" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="descripcion" type="xs:string" />
                <xs:element name="tipo" type="xs:string" />
                <xs:element name="genero" type="xs:string" />
                <xs:element name="estado">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="habilidades" type="xs:string" />
                            <xs:element name="destreza" type="xs:string" />
                            <xs:element name="nivel" type="xs:string" />
                            <xs:element name="fuerza" type="xs:string" />
                            <xs:element name="faseEvolucion" type="xs:string" />
                            <xs:element name="puntosVida" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="piepagina">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="p" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/ej09-pokeDAW/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- © Juan Galisteo | Todos los derechos reservados -->

<pokeDAW xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="index.xsd">
    <nombre>PokeDAW</nombre>
    <numeroPokedex>369</numeroPokedex>
    <imagen foto="pokedaw"></imagen>
    <descripcion>El Pokémon legendario y más fuerte de todos los tiempos.</descripcion>
    <tipo>psíquico</tipo>
    <genero>masculino</genero>

    <estado>
        <habilidades>Inteligencia, Sabiduría, Velocidad, Resistencia, Autodeterminación</habilidades>
        <destreza>33</destreza>
        <nivel>100</nivel>
        <fuerza>69</fuerza>
        <faseEvolucion>3</faseEvolucion>
        <puntosVida>127</puntosVida>
    </estado>

        <!-- PIE DE PÁGINA -->
    <piepagina>
        <p>© Juan Galisteo | Trabajo de clase: Configuración de Aplicación - DAW</p>
    </piepagina>
</pokeDAW>
