=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/ej10-estacionmeteorologica/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="estacionMeteorologica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ubicacion" type="xs:string" />
                <xs:element name="fecha" type="xs:string" />
                <xs:element name="hora" type="xs:string" />
                <xs:element name="temperatura">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="unidad" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="humedad">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="unidad" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="presion">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="unidad" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="viento">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="unidad" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lluvia">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="unidad" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="piepagina">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="p" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juangm1990/Lenguajes2024_JGalisteo/segundotrimestre/tema_11/ej10-estacionmeteorologica/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- © Juan Galisteo | Todos los derechos reservados -->

<estacionMeteorologica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="index.xsd">
    <ubicacion>Córdoba, España</ubicacion>
    <fecha>2025-01-14</fecha>
    <hora>18:33</hora>
    <temperatura unidad="°C">33.5</temperatura>
    <humedad unidad="%">65</humedad>
    <presion unidad="hPa">1015</presion>
    <viento unidad="km/h">33</viento>
    <lluvia unidad="mm">0</lluvia>

    <!-- PIE DE PÁGINA -->
    <piepagina>
        <p>© Juan Galisteo | Trabajo de clase: Configuración de Aplicación - DAW</p>
    </piepagina>
</estacionMeteorologica>
